// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLDE43QktyeFdRtkm1RHArUZy9PzEadf4',
    appId: '1:923927006659:android:46abf7aa84a8ab95a6c176',
    messagingSenderId: '923927006659',
    projectId: 'r2re-75417',
    storageBucket: 'r2re-75417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMC-dDEt_6hxYdSlYht4LQBW1wbEBsLF4',
    appId: '1:923927006659:ios:516e5984c3e22a1ba6c176',
    messagingSenderId: '923927006659',
    projectId: 'r2re-75417',
    storageBucket: 'r2re-75417.appspot.com',
    androidClientId: '923927006659-c7hv07rvv363q4v5i6mof3nbuhhakn8k.apps.googleusercontent.com',
    iosClientId: '923927006659-tkls50qd2b3m4sfe43qbb6opp7o6ulsm.apps.googleusercontent.com',
    iosBundleId: 'com.r2rekorea.r2reapp',
  );
}
